### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by name212**
Signed-off-by: Nikolay Mitrofanov <30695496+name212@users.noreply.github.com>

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by name212** [comment]
/e2e/failed/abort nmit-sts-10 refs/pull/217/head static;Static;containerd;1.21 3307535589 failed_cluster_state_static_containerd_1_21 3307535589-1-con-1-21 1288133299

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/failed/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...

**Comment by name212** [comment]
/e2e/failed/abort nmit-sts-10 refs/pull/217/head aws;WithoutNAT;containerd;1.21 3307667139 failed_cluster_state_aws_containerd_1_21 3307667139-1-con-1-21 1288141824

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/failed/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by name212** [comment]
/e2e/failed/abort nmit-sts-10 refs/pull/217/head static;Static;containerd;1.21 3315618999 failed_cluster_state_static_containerd_1_21 3315618999-1-con-1-21 217

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/failed/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by name212** [comment]
/e2e/failed/abort nmit-sts-10 refs/pull/217/head static;Static;containerd;1.21 3315795337 failed_cluster_state_static_containerd_1_21 3315795337-1-con-1-21 217

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/failed/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/aws'...

**Comment by name212** [comment]
/e2e/failed/abort nmit-sts-10 refs/pull/217/head aws;WithoutNAT;containerd;1.21 3315835572 failed_cluster_state_aws_containerd_1_21 3315835572-1-con-1-21 217

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/failed/abort' command and started the workflow...

**Pull request closed without merging**
