### PR TITLE
Update script.sh

### PR DESCRIPTION
**Pull request by name212**
Signed-off-by: Nikolay Mitrofanov <30695496+name212@users.noreply.github.com>

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by name212** [comment]
/e2e/failed/abort nmit-sts-10 refs/pull/219/head static;Static;containerd;1.21 3318283465 failed_cluster_state_static_containerd_1_21 3318283465-1-con-1-21 219

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/failed/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/static'...

**Comment by name212** [comment]
/e2e/failed/abort nmit-sts-10 refs/pull/219/head static;Static;containerd;1.21 3318434111 failed_cluster_state_static_containerd_1_21 3318434111-1-con-1-21 219

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/failed/abort' command and started the workflow...

**Pull request closed without merging**
