### PR TITLE
1

### PR DESCRIPTION
**Pull request by alexey-gavrilov-flant**
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/static'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort static;Static;containerd;1.27 10683015850 10683015850-1-con-1-27 /sys/deckhouse-oss/install:pr371-test-2

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/static'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort static;Static;containerd;1.27 10683232717 10683232717-1-con-1-27 /sys/deckhouse-oss/install:pr371-test-2

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/static'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort static;Static;containerd;1.27 10683670345 10683670345-1-con-1-27 /sys/deckhouse-oss/install:pr371-test-2

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort static;Static;containerd;1.27 10684148113 10684148113-1-con-1-27 /sys/deckhouse-oss/install:pr371-test-2

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/static'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort static;Static;containerd;1.27 10684521883 10684521883-1-con-1-27 /sys/deckhouse-oss/install:pr371-test-2

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/static'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort static;Static;containerd;1.27 10685578041 10685578041-1-con-1-27 /sys/deckhouse-oss/install:pr371-test-2 astra@192.168.199.77

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/static'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort static;Static;containerd;1.27 10686051458 10686051458-1-con-1-27 /sys/deckhouse-oss/install:pr371-test-2 astra@192.168.199.138

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/static'...

**Comment by alexey-gavrilov-flant** [comment]
/e2e/abort static;Static;containerd;1.27 10695961788 10695961788-1-con-1-27 /sys/deckhouse-oss/install:pr371-test-2 astra@192.168.199.58

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @alexey-gavrilov-flant. I've started the workflow for label 'e2e/run/static'...

**Pull request closed without merging**
