### PR TITLE
Update script.sh

### PR DESCRIPTION
**Pull request by name212**
Signed-off-by: Nikolay Mitrofanov <30695496+name212@users.noreply.github.com>

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [ ] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: <kebab-case of a module name> | <1st level dir in the repo>
type: fix | feature | chore
summary: <ONE-LINE of what effectively changes for a user>
impact: <what to expect for users, possibly MULTI-LINE>, required if impact_level is high ↓
impact_level: default | high | low
```

### CODE REVIEW

**Comment by name212** [comment]
/e2e/abort static;Static;containerd;1.21 3694435300 3694435300-1-con-1-21 /sys/deckhouse-oss/install:pr247-test-2

**Comment by name212** [comment]
/e2e/abort static;Static;containerd;1.21 3694435300 3694435300-1-con-1-21 /sys/deckhouse-oss/install:pr247-test-2

**Comment by name212** [comment]
/e2e/abort static;Static;containerd;1.21 3694071861 3694071861-1-con-1-21 /sys/deckhouse-oss/install:pr247-test-2

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've recognized your '/e2e/abort' command and started the workflow...

**Pull request closed without merging**
